# Generated by Django 4.0.2 on 2022-02-18 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BpEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messure_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
