# Generated by Django 4.0.2 on 2022-02-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodpressure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpentry',
            name='diastolic',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='bpentry',
            name='pulse',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='bpentry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bpentry',
            name='systolic',
            field=models.PositiveSmallIntegerField(default=130),
        ),
    ]
